# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export EDITOR="vim"

export PATH=$PATH:${HOME}/bin
export PATH=$PATH:${HOME}/.bin
export PATH=$PATH:${HOME}/.local/bin
export PATH=$PATH:${HOME}/.cargo/bin

export LS_COLORS="di=1;36:ln=0;44:so=32:pi=31:ex=35:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"
export TERM=xterm-256color

# autoswitch_virtualenv settings
export AUTOSWITCH_SILENT=true

# poetry shit
export POETRY_VIRTUALENVS_IN_PROJECT=true
export POETRY_NO_INTERACTION=true

# silence the annoying direnv logs (we already have the p10k direnv segment)
export DIRENV_LOG_FORMAT=

# homebrew isn't added to path by default for m1 macbooks
if test -f "/opt/homebrew/bin/brew"; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# oh-my-zsh settings
export ZSH="$HOME/.oh-my-zsh"
zstyle ':omz:update' mode disabled  # disable automatic updates for oh-my-zsh
export DISABLE_AUTO_TITLE="true"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(
    zoxide
    direnv
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-fzf-history-search
    colored-man-pages
    git-open
    gitignore
    autoswitch_virtualenv
)

# load oh-my-zsh but ignore any aliases it sets
save_aliases=$(alias -L)
source $ZSH/oh-my-zsh.sh
unalias -m '*'
eval $save_aliases
unset save_aliases

# load powerlevel10k config
source ${HOME}/.p10k.zsh

# terminal title
echo -ne "\033];terminal\007"

# HISTFILE=~/.zsh_history
export HISTSIZE=1024000
export SAVEHIST=1024000

# zsh options
# type setopt in terminal for active settings
# (https://linux.die.net/man/1/zshoptions)
# (https://www.csse.uwa.edu.au/programming/linux/zsh-doc/zsh_17.html)
unsetopt BEEP
bindkey '^[^[[D' backward-word
bindkey '^[^[[C' forward-word

# better history (https://coderwall.com/p/jpj_6q/zsh-better-history-searching-with-arrow-keys)
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down
bindkey "^[p" history-beginning-search-backward
bindkey "^[n" history-beginning-search-forward

# ocaml init
[[ ! -r "$HOME/.opam/opam-init/init.zsh" ]] || source "$HOME/.opam/opam-init/init.zsh"  > /dev/null 2> /dev/null

source "${HOME}/.functions"
source "${HOME}/.aliases"

[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"

