# p10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# load aliases and init
source ${HOME}/.init
source ${HOME}/.aliases


# autoswitch_virtualenv message (must be loaded before plugins)
AUTOSWITCH_SILENT=true


# oh-my-zsh settings
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(
    z
    zsh-autosuggestions
    zsh-syntax-highlighting
    colored-man-pages
    gitignore
    # pyenv
    direnv
    gcloud
    docker
    github
    rbenv
    autoswitch_virtualenv
)


# load oh-my-zsh while ignoring aliases
save_aliases=$(alias -L)
source $ZSH/oh-my-zsh.sh
unalias -m '*'
eval $save_aliases
unset save_aliases

# readd aliases that I actually do want
alias ${_Z_CMD:-z}='_z 2>&1'
alias git=hub


# load powerlevel10k config
source ${HOME}/.p10k.zsh


# terminal title
export DISABLE_AUTO_TITLE="true"
echo -ne "\033];terminal\007"


# terminal colors
export TERM=xterm-256color


# HISTFILE=~/.zsh_history
HISTSIZE=64000
SAVEHIST=64000

unsetopt BEEP

# zsh options
# type setopt in terminal for active settings
# (https://linux.die.net/man/1/zshoptions)
# (https://www.csse.uwa.edu.au/programming/linux/zsh-doc/zsh_17.html)

# # don't expand aliases _before_ completion has finished
# #   like: git comm-[tab]
# setopt complete_aliases

bindkey '^[^[[D' backward-word
bindkey '^[^[[C' forward-word
# bindkey '^[[5D' beginning-of-line
# bindkey '^[[5C' end-of-line
# bindkey '^[[3~' delete-char
# bindkey '^?' backward-delete-char

# better history (https://coderwall.com/p/jpj_6q/zsh-better-history-searching-with-arrow-keys)
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down
bindkey "^[p" history-beginning-search-backward
bindkey "^[n" history-beginning-search-forward

# TEMPORORARY FIX
# todo: remove this once the bug is fixed, see https://github.com/ohmyzsh/ohmyzsh/issues/10013
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
