#!/usr/bin/env bash

# get root priveleges
sudo -v

set -e

# set default dotfiles root and override it with value set in .localrc (if it exists)
export DOTFILES_ROOT=${HOME}/.dotfiles
if [[ -a ${HOME}/.localrc ]]; then
    source ${HOME}/.localrc &> /dev/null
fi

if [ ! -d "$DOTFILES_ROOT" ] ; then
    echo "ERROR"
    echo "-----"
    echo "dotfiles root directory was not found: $DOTFILES_ROOT"
    echo "stopping install ..."
    echo ""
    echo "if you are not using the default location (${HOME}/.dotfiles), please specify"
    echo "the location via the DOTFILES_ROOT env variable in ${HOME}/.localrc:"
    echo "    export DOTFILES_ROOT=\"/custom/path/to/dotfiles\""
    echo ""
    return
fi

cd ${DOTFILES_ROOT}

# check os and install accordingly
if test "$(uname)" = "Darwin"; then
    sudo sh macos/install.sh
elif test "$(uname)" = "Linux"; then
    sudo sh linux/install.sh
else
    echo "os must be darwin (macos) or linux"
    exit 1
fi

# run setup.sh files
for file in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name 'setup.sh' -not -path '*.git*'); do
    sh $file
done

# symlink dotfiles
./dotfiles
