#!/usr/bin/env bash

# get root privileges
sudo -v

# add $DOTFILES_ROOT to env vars
DOTFILES_ROOT="~/.dotfiles"
echo "export DOTFILES_ROOT=\"$DOTFILES_ROOT\"" >> ~/.localrc
source ~/.localrc

# get dotfiles repo
curl -LO https://github.com/jaymody/dotfiles/archive/master.zip
unzip master.zip
rm master.zip
mv dotfiles-master $DOTFILES_ROOT
cd $DOTFILES_ROOT

# install
./install

# dotfiles
./dotfiles
