#!/usr/bin/env bash

# get root priveleges
sudo -v

set -e

if [ -z "$DOTFILES_ROOT" ] ; then
  echo "DOTFILES_ROOT is not set, terminating ..."
  exit 1
elif [ ! -d "$DOTFILES_ROOT" ] ; then
  echo "Directory for DOTFILES_ROOT does not exist: $DOTFILES_ROOT"
  echo "terminating ..."
  exit 1
fi

cd ${DOTFILES_ROOT}

# install macos settings
sudo sh macos/install.sh

# install brew
sudo sh brew/install.sh

# install zsh
sudo sh zsh/install.sh

# install docker
sudo sh docker/install.sh
