#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

if [ -z "$DOTFILES_ROOT" ] ; then
  echo "DOTFILES_ROOT is not set, terminating ..."
  exit 1
fi

cd ${DOTFILES_ROOT}

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
