#!/usr/bin/env bash

# check zsh is installed
if ! [ -x "$(command -v zsh)" ]; then
    echo "ERROR: zsh is not installed"
    exit
fi

# install oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
export KEEP_ZSHRC=yes
export RUNZSH=no
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# install plugins/themes
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH}/custom/themes/powerlevel10k"
git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions "${ZSH}/custom/plugins/zsh-autosuggestions"
git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git "${ZSH}/custom/plugins/zsh-syntax-highlighting"
git clone --depth=1 https://github.com/paulirish/git-open.git "${ZSH}/custom/plugins/git-open"
git clone --depth=1 https://github.com/jaymody/zsh-autoswitch-virtualenv.git "${ZSH}/custom/plugins/autoswitch_virtualenv"
